# Generated by Django 4.0.3 on 2022-03-31 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aeromobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(max_length=20)),
                ('modello', models.CharField(max_length=20)),
                ('posti_prima', models.IntegerField()),
                ('posti_seconda', models.IntegerField()),
                ('posti_economy', models.IntegerField()),
                ('percorrenza', models.IntegerField()),
                ('stato', models.BooleanField()),
                ('ultima_manutenzione', models.DateField()),
                ('km_percorsi', models.IntegerField()),
                ('personale_pilota', models.IntegerField()),
                ('personale_assistenza', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Aeroporto',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('continent', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('gps_code', models.CharField(max_length=20)),
                ('iata_code', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Personale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=10)),
                ('cognome', models.CharField(max_length=10)),
                ('mansione', models.CharField(max_length=20)),
                ('codice_personale', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Volo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aeroporto_partenza', models.CharField(max_length=20)),
                ('aeroporto_arrivo', models.CharField(max_length=20)),
                ('ora_partenza', models.FloatField()),
                ('ora_arrivo', models.FloatField()),
                ('posti', models.IntegerField()),
                ('scheduling', models.DateField()),
                ('codice_volo', models.CharField(max_length=10)),
                ('operatore', models.CharField(max_length=20)),
                ('aeromobile', models.CharField(max_length=15)),
                ('distanza', models.IntegerField()),
                ('personale_volo', models.CharField(max_length=20)),
                ('personale_assistenza', models.CharField(max_length=20)),
            ],
        ),
    ]
