# Generated by Django 4.0.3 on 2022-04-01 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aeroporto', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aeroporto',
            old_name='name',
            new_name='nome',
        ),
    ]
