# Generated by Django 4.0.3 on 2022-04-05 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aeroporto', '0002_rename_name_aeroporto_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aeroporto',
            name='iata_code',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='aeroporto',
            name='nome',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='personale',
            name='nome',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='volo',
            name='aeroporto_arrivo',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='volo',
            name='aeroporto_partenza',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='volo',
            name='personale_assistenza',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='volo',
            name='personale_volo',
            field=models.IntegerField(),
        ),
    ]
