# Generated by Django 4.0.3 on 2022-04-06 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aeroporto', '0004_remove_volo_aeromobile_remove_volo_distanza_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volo',
            name='aeroporto_arrivo',
            field=models.CharField(max_length=200),
        ),
    ]
