# Generated by Django 4.0.3 on 2022-04-06 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aeroporto', '0005_alter_volo_aeroporto_arrivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personale',
            name='codice_personale',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='personale',
            name='cognome',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='personale',
            name='mansione',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='personale',
            name='nome',
            field=models.CharField(max_length=200),
        ),
    ]
