# Generated by Django 4.0.3 on 2022-04-07 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aeroporto', '0007_rename_data_volo_data_partenza_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volo',
            name='solo_ritorno',
        ),
        migrations.AlterField(
            model_name='aeromobile',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='personale',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='volo',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
