# Generated by Django 4.0.3 on 2022-04-07 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aeroporto', '0008_remove_volo_solo_ritorno_alter_aeromobile_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aeromobile',
            name='posti_economy',
        ),
        migrations.RemoveField(
            model_name='aeromobile',
            name='posti_prima',
        ),
        migrations.RemoveField(
            model_name='aeromobile',
            name='posti_seconda',
        ),
    ]
