# Generated by Django 4.0.3 on 2022-04-07 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aeroporto', '0010_alter_aeromobile_id_alter_volo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aeromobile',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
