# Generated by Django 4.0.3 on 2022-04-08 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aeroporto', '0011_alter_aeromobile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volo',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
