# Generated by Django 4.0.3 on 2022-04-21 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aeroporto', '0012_alter_volo_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prenotazione',
            fields=[
                ('id_prenotazione', models.IntegerField(primary_key=True, serialize=False)),
                ('posto_selezionato', models.CharField(max_length=5)),
                ('volo_corrispondente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aeroporto.volo')),
            ],
        ),
    ]
