# Generated by Django 4.0.3 on 2022-04-21 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aeroporto', '0013_prenotazione'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prenotazione',
            old_name='volo_corrispondente',
            new_name='id_volo_corrispondente',
        ),
        migrations.AddField(
            model_name='prenotazione',
            name='id_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
