# Generated by Django 4.0.3 on 2022-04-21 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aeroporto', '0014_rename_volo_corrispondente_prenotazione_id_volo_corrispondente_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prenotazione',
            old_name='id_prenotazione',
            new_name='id',
        ),
    ]
