# Generated by Django 4.0.3 on 2022-04-24 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aeroporto', '0015_rename_id_prenotazione_prenotazione_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prenotazione',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
