# Generated by Django 4.0.3 on 2022-04-24 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aeroporto', '0016_alter_prenotazione_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prenotazione',
            name='id_user',
        ),
        migrations.RemoveField(
            model_name='prenotazione',
            name='id_volo_corrispondente',
        ),
        migrations.AddField(
            model_name='prenotazione',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prenotazione',
            name='volo_corrispondente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aeroporto.volo'),
        ),
        migrations.AlterField(
            model_name='prenotazione',
            name='posto_selezionato',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
