# Generated by Django 4.0.3 on 2022-04-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aeroporto', '0017_remove_prenotazione_id_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prenotazione',
            name='posto_selezionato',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
