# Generated by Django 4.0.3 on 2022-04-24 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aeroporto', '0018_alter_prenotazione_posto_selezionato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prenotazione',
            name='posto_selezionato',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='prenotazione',
            name='user',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prenotazione',
            name='volo_corrispondente',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aeroporto.volo'),
        ),
    ]
